server:
  port: 8003

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #数据库连接驱动包
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zxd8421

mybatis:
  mapper-locations: classpath:Mapper/**/*.xml
  type-aliases-package: com.zxd.Pojo

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment-8003
    prefer-ip-address: true #显示ip地址