server:
  port: 9002

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh #路由ID，没有固定的规则但是要求唯一，建议配合服务器名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT #匹配后微服务名称，lb意思是loadBalance负载均衡
          predicates:
            - Path=/payment/get/** #断言，路径相匹配进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates: #多种限制条件 匹配规则
            - Path=/payment/getPort/**
            - After=2021-10-16T14:11:13.168+08:00[Asia/Shanghai]
            - Cookie=username,zxd # 增加cookie username=zxd 如果没有不予访问
            - Header=X-Request-Id,\d+ #请求头要有X-request-Id属性 并且为蒸熟的正则表达式
#            - Method=GET #设置方法
#            - Query=username,\d+ #要有参数名字username并且值还要是正数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/