server:
  port: 3355

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: config-client-3355
    prefer-ip-address: true #显示ip地址

management:
  endpoints:
    web:
      exposure:
        include: "*"