server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:FreeGuest0/spring-cloud-config.git
          uri: https://github.com/FreeGuest0/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
#          force-pull: true
          username: 1064024659@qq.com
          password: zhang7605391
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: config-center-3344
    prefer-ip-address: true #显示ip地址