server:
  port: 8007

spring:
  application:
    name: cloud-consul-consumer-order8007
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}